- name: Get region
  uri:
    url: http://169.254.169.254/computeMetadata/v1/instance/zone
    headers:
      Metadata-Flavor: Google
    return_content: yes
  register: gcp_region

- name: Set variable "region"
  set_fact:
    cloud: gcp
    region: "{{ gcp_region.content.split('/') | last }}"




