- name: Download dcos_install.py
  get_url:
    url: "http://{{ hostvars[groups.dcos_bootstrap.0].ansible_default_ipv4.address }}/dcos_install.sh"
    dest: /tmp/dcos_install.sh
    mode: 0777
  when: install.dcos

- name: Execute dcos_install.sh
  shell: /tmp/dcos_install.sh slave
  args:
    chdir: /tmp
    executable: /bin/bash
  become: true
  retries: "{{ max_retries }}"
  when: install.dcos

