- name: Install dependencies
  yum:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - perl
    - authd
    - fuse-libs
    - lsof
    - perl-JSON
    - ftp://ftp.pbone.net/mirror/ftp.centos.org/7.5.1804/cloud/x86_64/openstack-ocata/common/python-jsonschema-2.3.0-1.el7.noarch.rpm
    - http://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/p/python2-psutil-2.2.1-3.el7.x86_64.rpm

- name: Get private IP address
  set_fact:
    host_ip: "{{ hostvars[inventory_hostname]['ansible_%s'|format(ansible_default_ipv4.interface)].ipv4.address }}"

- name: Remove existing hostname mapping of the private IP address
  lineinfile:
    path: /etc/hosts
    regexp: "^{{ host_ip }}.*"
    state: absent
  become: true

- name: Replace hostname with the private IP address in /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ host_ip }}\t{{ host_ip }}\t{{ host_ip }}"
  become: true

- name: Have hostname change take effect immediately
  hostname:
    name: "{{ host_ip }}"
  become: true









