- name: Deploy MongoDB
  uri:
    url: "http://{{ hostvars[inventory_hostname]['ansible_%s'|format(ansible_default_ipv4.interface)].ipv4.address }}:8080/v2/apps"
    body: "{{ lookup('template', 'mongodb.json.j2') | to_json }}"
    body_format: json
    status_code: 201
    method: POST

- name: Deploy PIVOT
  uri:
    url: "http://{{ hostvars[inventory_hostname]['ansible_%s'|format(ansible_default_ipv4.interface)].ipv4.address }}:8080/v2/apps"
    body: "{{ lookup('template', 'pivot.json.j2') | to_json }}"
    body_format: json
    status_code: 201
    method: POST

