- name: Add tunnel
  template:
    src: ipsec.conf.j2
    dest: /etc/ipsec.conf
    force: yes
  become: true

- name: Restart IPSec
  systemd:
    state: restarted
    daemon_reload: yes
    name: ipsec
  become: true
